name: Flutter CI
on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build_apk:
    name: Build Flutter (Android)
    runs-on: macos-latest
    strategy: # we are using strategy if we need to run on parallel with different devices and version
      matrix:
        api-level: [25] #Google api level for example [25,23,28] 
        target: [default]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Install Android Emulator
        uses: reactivecircus/android-emulator-runner@v1 # install and create the Emulator
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
      - name: Install and Run Appium Server
        run: |
          chmod +x ./scripts/RunAppiumServer.sh 
          ./scripts/RunAppiumServer.sh
      - name: Clean up
        run: flutter clean
      - name: Get Dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --debug 
      - uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
      
  
